# Generated by Django 5.1.6 on 2025-03-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_userprofile_created_at_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerletter',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='offerletter',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
