# Generated by Django 5.1.6 on 2025-03-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_offerletter_department_alter_offerletter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='office_criteria/'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule',
            field=models.TextField(blank=True, null=True),
        ),
    ]
