# Generated by Django 5.1.6 on 2025-03-03 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_customuser_otptoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otptoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='OtpToken',
        ),
    ]
