# Generated by Django 5.1.6 on 2025-03-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_teammember_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('emp_code', models.CharField(max_length=50)),
                ('leave_from', models.DateField()),
                ('leave_till', models.DateField()),
                ('no_of_days', models.IntegerField()),
                ('purpose', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='user',
        ),
    ]
