# Generated by Django 5.1.6 on 2025-03-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_leaveapplication_permissionapplication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('emp_code', models.CharField(max_length=100)),
                ('leave_from', models.TimeField()),
                ('leave_till', models.TimeField()),
                ('no_of_days', models.PositiveIntegerField()),
                ('purpose', models.TextField()),
                ('leave_on', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('emp_code', models.CharField(max_length=100)),
                ('permission_from', models.TimeField()),
                ('permission_till', models.TimeField()),
                ('no_of_hours', models.PositiveIntegerField()),
                ('purpose', models.TextField()),
                ('permission_on', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='LeaveApplication',
        ),
        migrations.DeleteModel(
            name='PermissionApplication',
        ),
    ]
