# Generated by Django 5.1.6 on 2025-03-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_leaveapplication_permissionapplication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='designation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='emp_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_on',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='permissionapplication',
            name='designation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='permissionapplication',
            name='emp_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='permissionapplication',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='permissionapplication',
            name='permission_on',
            field=models.CharField(max_length=255),
        ),
    ]
