# Generated by Django 5.1.6 on 2025-03-07 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_leaveapplication_designation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveApplication',
        ),
        migrations.DeleteModel(
            name='PermissionApplication',
        ),
    ]
