# Generated by Django 5.1.5 on 2025-03-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_delete_leaveapplication_delete_permissionapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('emp_code', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('leave_from', models.TimeField()),
                ('leave_till', models.TimeField()),
                ('no_of_days', models.PositiveIntegerField()),
                ('purpose', models.TextField()),
                ('leave_on', models.CharField(choices=[('OD', 'OD (On Duty)'), ('LOP', 'LOP (Loss of Pay)'), ('Others', 'Others')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('emp_code', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('permission_from', models.TimeField()),
                ('permission_till', models.TimeField()),
                ('no_of_hours', models.PositiveIntegerField()),
                ('purpose', models.TextField()),
                ('permission_on', models.CharField(choices=[('OD', 'OD (On Duty)'), ('LOP', 'LOP (Loss of Pay)'), ('Others', 'Others')], max_length=50)),
            ],
        ),
    ]
