# Generated by Django 5.1.5 on 2025-03-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_leaveapplication_emp_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='designation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_on',
            field=models.CharField(choices=[('OD', 'On Duty'), ('LOP', 'Loss of Pay'), ('Others', 'Others')], max_length=6),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='permissionapplication',
            name='designation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='permissionapplication',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='permissionapplication',
            name='permission_on',
            field=models.CharField(choices=[('OD', 'On Duty'), ('LOP', 'Loss of Pay'), ('Others', 'Others')], max_length=6),
        ),
    ]
