# Generated by Django 5.1.6 on 2025-03-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_delete_leaveapplication_delete_permissionapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('emp_code', models.CharField(max_length=50)),
                ('leave_from', models.TimeField()),
                ('leave_till', models.TimeField()),
                ('no_of_days', models.IntegerField()),
                ('purpose', models.TextField()),
                ('leave_on', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('emp_code', models.CharField(max_length=50)),
                ('permission_from', models.TimeField()),
                ('permission_till', models.TimeField()),
                ('no_of_hours', models.IntegerField()),
                ('purpose', models.TextField()),
                ('permission_on', models.CharField(max_length=50)),
            ],
        ),
    ]
