# Generated by Django 5.1.6 on 2025-03-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_leaveapplication_permissionapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='emp_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_on',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='permissionapplication',
            name='emp_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='permissionapplication',
            name='permission_on',
            field=models.CharField(max_length=100),
        ),
    ]
