# Generated by Django 5.1.6 on 2025-03-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_leaveapplication_emp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='permissionapplication',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
