# Generated by Django 5.1.6 on 2025-03-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_till',
            field=models.DateField(),
        ),
    ]
