# Generated by Django 5.1.6 on 2025-03-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_leaveapplication_leave_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emp_code', models.CharField(max_length=20, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=100)),
                ('experience', models.FloatField()),
                ('mobile_num', models.CharField(max_length=15)),
                ('mail_id', models.EmailField(max_length=254)),
            ],
        ),
    ]
