# Generated by Django 5.1.6 on 2025-03-21 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_employeedetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeDetails',
        ),
    ]
