# Generated by Django 5.1.6 on 2025-03-21 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_delete_employeedetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('emp_code', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('designation', models.CharField(max_length=255)),
                ('blood_grp', models.CharField(max_length=10)),
                ('personal_num', models.CharField(max_length=15)),
                ('official_num', models.CharField(max_length=15)),
                ('emergency_num', models.CharField(max_length=15)),
                ('date_of_join', models.DateField()),
                ('experience', models.CharField(max_length=100)),
                ('skill', models.TextField()),
                ('mail_id', models.EmailField(max_length=254)),
                ('adhar_num', models.CharField(max_length=20)),
                ('pan_num', models.CharField(max_length=20)),
                ('visa', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
