# Generated by Django 5.1.5 on 2025-03-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_employeedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelievingFormality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_data', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='user',
        ),
        migrations.DeleteModel(
            name='RelievingRule',
        ),
        migrations.DeleteModel(
            name='EmployeeDetails',
        ),
    ]
